# Generated by Django 4.2.3 on 2023-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contrat', models.CharField(max_length=100)),
                ('Déléguant', models.CharField(max_length=100)),
                ('Délégataire', models.CharField(max_length=100)),
                ('Semestre', models.DateField()),
                ('Datevisa', models.DateField()),
                ('Durée', models.IntegerField()),
                ('Datededémarrage', models.DateField()),
            ],
        ),
    ]
