# Generated by Django 4.1.7 on 2023-08-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='Datededémarrage',
            new_name='datededémarrage',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='Datevisa',
            new_name='datevisa',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='Durée',
            new_name='durée',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='Semestre',
            new_name='semestre_debut',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='Contrat',
            new_name='titreducontrat',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='id',
        ),
        migrations.AddField(
            model_name='contrat',
            name='contrat_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='semestre_fin',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Perimetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communesdesservies', models.IntegerField()),
                ('populationdesservie', models.IntegerField()),
                ('longueur_réseau', models.IntegerField()),
                ('nombre_lignes', models.IntegerField()),
                ('lignesurbaines', models.IntegerField()),
                ('lignespériphériques', models.IntegerField()),
                ('contrat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Energie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consommation_moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consommation_carurbant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consommation_electricite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emission_carbone', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contrat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat')),
            ],
        ),
    ]
