# Generated by Django 4.1.7 on 2023-08-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_rename_datededémarrage_contrat_datededémarrage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='Délégataire',
            new_name='délégataire',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='Déléguant',
            new_name='déléguant',
        ),
    ]
