# Generated by Django 4.2.3 on 2023-08-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0005_alter_contrat_contrat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commerciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbvoyageurs', models.IntegerField()),
                ('nbplacesvides', models.IntegerField()),
                ('totalvoyageursannuels', models.IntegerField()),
                ('tauxremplissage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tauxtransportvide', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ticketsvendussemestre', models.IntegerField()),
                ('tarifscolaire', models.IntegerField()),
                ('tarifnormal', models.IntegerField()),
                ('tarifconventions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commercialesecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parcours_semestriel', models.IntegerField()),
                ('moyenne_par_ligne', models.IntegerField()),
                ('trajet_le_plus_long', models.IntegerField()),
                ('trajet_le_plus_court', models.IntegerField()),
                ('temps_max_trajet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temps_min_trajet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frequence_passage', models.IntegerField()),
                ('vitesse_commerciale', models.IntegerField()),
                ('ponctualite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horaire_debut', models.TimeField()),
                ('horaire_fin', models.TimeField()),
                ('heure_arret_service', models.TimeField()),
                ('pannes_bus', models.IntegerField()),
                ('accidents_bus', models.IntegerField()),
                ('delai_evacuation_panne', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
