# Generated by Django 4.2.3 on 2023-08-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0008_alter_commercialesecond_heure_arret_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialesecond',
            name='heure_arret_service',
        ),
    ]
