# Generated by Django 4.2.3 on 2023-08-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0009_remove_commercialesecond_heure_arret_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialesecond',
            name='heure_arret_service',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
