# Generated by Django 4.2.3 on 2023-08-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0011_remove_commercialesecond_accidents_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialesecond',
            name='accidents_bus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
