# Generated by Django 4.2.3 on 2023-08-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0014_commercialseconde_delete_commercialesecond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialseconde',
            old_name='heure_arret_service',
            new_name='heure_aret_service',
        ),
    ]
