# Generated by Django 4.2.3 on 2023-08-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0015_rename_heure_arret_service_commercialseconde_heure_aret_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialseconde',
            name='heure_aret_service',
        ),
        migrations.AddField(
            model_name='commercialseconde',
            name='heure_arret_service',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
