# Generated by Django 4.2.3 on 2023-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0016_remove_commercialseconde_heure_aret_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialseconde',
            name='heure_arret_service',
            field=models.IntegerField(),
        ),
    ]
