# Generated by Django 4.2.3 on 2023-08-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0017_alter_commercialseconde_heure_arret_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commercialseconde',
        ),
    ]
