# Generated by Django 4.2.3 on 2023-08-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0019_commercialseconde'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commercialseconde',
        ),
    ]
