# Generated by Django 4.2.3 on 2023-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0023_delete_commercialseconde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercialseconde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parcours_semestriel', models.IntegerField()),
                ('moyenne_par_ligne', models.IntegerField()),
                ('trajet_le_plus_long', models.IntegerField()),
                ('trajet_le_plus_court', models.IntegerField()),
                ('temps_max_trajet', models.IntegerField()),
                ('temps_min_trajet', models.IntegerField()),
                ('frequence_passage', models.IntegerField()),
                ('vitesse_commerciale', models.IntegerField()),
                ('ponctualite', models.IntegerField()),
                ('horaire_debut', models.IntegerField()),
                ('horaire_fin', models.IntegerField()),
                ('heure_arret_service', models.IntegerField()),
                ('pannes_bus', models.IntegerField()),
                ('accidents_bus', models.IntegerField()),
                ('delai_evacuation_panne', models.IntegerField()),
            ],
        ),
    ]
