# Generated by Django 4.2.3 on 2023-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0024_commercialseconde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialseconde',
            name='delai_evacuation_panne',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='commercialseconde',
            name='horaire_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='commercialseconde',
            name='horaire_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='commercialseconde',
            name='ponctualite',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='commercialseconde',
            name='temps_max_trajet',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='commercialseconde',
            name='temps_min_trajet',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
