# Generated by Django 4.2.3 on 2023-08-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0025_alter_commercialseconde_delai_evacuation_panne_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commercialseconde',
        ),
    ]
