# Generated by Django 4.2.3 on 2023-08-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0026_delete_commercialseconde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercialseconde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parcours_semestriel', models.IntegerField()),
                ('moyenne_par_ligne', models.IntegerField()),
                ('trajet_le_plus_long', models.IntegerField()),
                ('trajet_le_plus_court', models.IntegerField()),
                ('temps_max_trajet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temps_min_trajet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frequence_passage', models.IntegerField()),
                ('vitesse_commerciale', models.IntegerField()),
                ('ponctualite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horaire_debut', models.TimeField()),
                ('horaire_fin', models.TimeField()),
                ('heure_arret_service', models.IntegerField()),
                ('pannes_bus', models.IntegerField()),
                ('accidents_bus', models.IntegerField()),
                ('delai_evacuation_panne', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
