# Generated by Django 4.2.3 on 2023-08-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0029_commercialseconde'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerciale',
            name='contrat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat'),
        ),
        migrations.AddField(
            model_name='commercialseconde',
            name='contrat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat'),
        ),
        migrations.AlterField(
            model_name='energie',
            name='contrat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat'),
        ),
        migrations.AlterField(
            model_name='perimetre',
            name='contrat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat'),
        ),
    ]
