# Generated by Django 4.2.3 on 2023-08-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0030_commerciale_contrat_id_commercialseconde_contrat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('partenaire_id', models.AutoField(primary_key=True, serialize=False)),
                ('partenaire_nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_investissement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_bus', models.IntegerField()),
                ('nombre_abris', models.IntegerField()),
                ('nombre_arrets', models.IntegerField()),
                ('nombre_aires_stationnement', models.IntegerField()),
                ('contrat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat')),
                ('partenaire_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrats.partenaire')),
            ],
        ),
    ]
