# Generated by Django 4.2.3 on 2023-08-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0032_alter_investissement_partenaire_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investissement',
            name='partenaire_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrats.partenaire'),
        ),
    ]
