# Generated by Django 4.2.3 on 2023-08-16 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0034_delete_investissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_investissement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_bus', models.IntegerField()),
                ('nombre_abris', models.IntegerField()),
                ('nombre_arrets', models.IntegerField()),
                ('nombre_aires_stationnement', models.IntegerField()),
                ('contrat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat')),
                ('partenaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrats.partenaire')),
            ],
        ),
    ]
